### PR TITLE
feat(contractHost): support new moduleFormat bundling

### PR DESCRIPTION
**Pull request by michaelfig**
Please see this change to make the contractHost compatible with the new `ag-solo upload-contract` bundling mechanism.

### CODE REVIEW

**Comment by katelynsills** [comment]
Hi Michael, I have some questions. When would we use the two `moduleFormat`s? What is each intended for?  

It looks like some of the code in the `moduleFormat === 'getExport'` case is similar to the code in `extractCheckFunction`. Is that on purpose?

**Comment by michaelfig** [comment]
> Hi Michael, I have some questions. When would we use the two `moduleFormat`s? What is each intended for?

The default `moduleFormat`, `"object"` is to maintain compatibility with current uses (if there are any).
 
> It looks like some of the code in the `moduleFormat === 'getExport'` case is similar to the code in `extractCheckFunction`. Is that on purpose?

Yes, the check functions are extracted from the exported namespace, but they are already functions, not source strings.

**Comment by erights** [comment]
Since the new moduleFormat is specific to rollup, should we give it a less generic name than `getExport`?

**Comment by erights** [comment]
Does something test this new case?

**Comment by erights** [comment]
Nevermind. I see https://github.com/Agoric/cosmic-swingset/pull/91

**Comment by michaelfig** [comment]
> Since the new moduleFormat is specific to rollup, should we give it a less generic name than `getExport`?

Actually, the `getExport()` wrapping of the rollup code is something that originated with SwingSet, and theoretically could apply also to non-rollup bundlers, too.  It's for any code for which:

```js
const moduleNamespace = getExport();
```

So I'm inclined to leave it as-is.

Thanks!

**Pull request merged**
