### PR TITLE
WIP: issuer operations preserve pipeline order

### PR DESCRIPTION
**Pull request by erights**
Use Promise.antiResolve from https://github.com/Agoric/eventual-send/pull/24 to keep issuer operations ordered without disrupting promise pipelining.

Would be a general technique for preserving pipelining over remote argument passing.

### CODE REVIEW

**Comment by michaelfig** [comment]
This looks really good!  It's a useful optimisation and doesn't interfere with other naive uses of handled Promises.

Can you explain why you chose the `R` suffix in `srcPaymentR` (i.e. what it stands for)?

**Comment by katelynsills** [comment]
Oh, this is interesting. What is anti-resolve?

**Comment by michaelfig** [comment]
@erights' invention to be able to synchronously fetch the resolved value for a handled promise.  It returns `undefined` if the handled promise has not yet been resolved (or if it is not a handled promise).

I'm suggesting it be called `Promise.getPresence(myPromise)`.

**Comment by erights** [comment]
> Can you explain why you chose the R suffix in srcPaymentR (i.e. what it stands for)?

Suggestion from @Chris-Hibbert 👍 

"R" for remote, but means "Not known to be local"
"P" for promise, but means, "Not known not to be a Promise and not known not to be remote"

This example itself demonstrates that, given `getPresence` (aka `antiResolve`), "R" does not imply that you do know it not to be a promise. It does imply that you know it to be one of:
   * A local object
   * A presence
   * A handled promise from which the non-thenable (local object or presence) is synchronously available.

"P" and "R" are not great for these. We need to bikeshed on our naming conventions.

**Comment by michaelfig** [comment]
Should `antiResolve` return whatever was the fulfilment of the handler was, or only presences?  That may help indicate a good name.

**Comment by erights** [comment]
> Should antiResolve return whatever was the fulfilment of the handler was, or only presences? That may help indicate a good name.

Whatever the fulfillment was. In the motivating case, payment arguments, the payments in question are the actual ones, not presences for them.

**Comment by michaelfig** [comment]
Maybe `Promise.getResolution(somethingR)`, or `Promise.getFulfilment(somethingR)` (though the latter will definitely cause people to misspell it).

**Comment by erights** [comment]
Obsolete

**Pull request closed without merging**
