### PR TITLE
Fix typo in chainmail

### PR DESCRIPTION
**Pull request by erights**
Missed closing a comment. This did not lead to a parsing error because c-like `/*` block comments don't nest. Within a c-like `/*` block comment, we should consider making the occurrence of a `/*` an error, since both the nesting or non-nesting behaviors are confusing.

### CODE REVIEW

**Comment by dckc** [comment]
parsing error? You have a chainmail parser? Or are you using capnproto tools somehow? Care to add a script to `package.json` to show how you're doing it?

**Comment by erights** [comment]
> parsing error? You have a chainmail parser?

@dckc , we do!

@michaelfig @Chris-Hibbert , where can Dan find the chainmail parser and how can he run it?

**Comment by michaelfig** [comment]
@dckc, it's not yet ready for primetime, but you can:

```
$ git clone -b chainmail https://github.com/Agoric/jessica
$ jessica/lang/nodejs/cmparse.bat [single .chainmail file]
```

That spits out an AST or a parse error, which is as far as we got.  The Chainmail quasi-parser is in https://github.com/Agoric/jessica/tree/chainmail/lib/quasi-chainmail.js.ts

**Comment by Chris-Hibbert** [comment]
I get 
jessica/lang/nodejs/cmparse.bat ERTP/core/issuers.chainmail 
added 512 packages from 407 contributors and audited 476955 packages in 8.115s
found 7050 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/Users/chrishibbert/jessica/lang/nodejs/cmparse.js:1
**Error: Cannot find module '@michaelfig/slog'**
Require stack:
- /Users/chrishibbert/jessica/lang/nodejs/cmparse.js
    at Object.<anonymous> (/Users/chrishibbert/jessica/lang/nodejs/cmparse.js:1)

**Comment by michaelfig** [comment]
@Chris-Hibbert, I updated the instructions above to include an `npm install`.  That should fix your problem.

Sorry for not adequately testing this before I posted!

**Comment by Chris-Hibbert** [comment]
There's a parse error in assays. I'll fix it.

**Pull request closed without merging**
